/* আল-কুরআন গবেষণা — Chat System v2.8
   Stable mobile chat + voice + modes + abort + retry + local fallback.
   Backend remains Cloudflare Worker; UI does not claim unverified data as verified.
*/
(function(){
'use strict';
const modes=[['general','💬 সাধারণ প্রশ্ন'],['word','🔎 শব্দ গবেষণা'],['ayah','🧩 আয়াত বিশ্লেষণ'],['math','📊 গাণিতিক গবেষণা'],['concordance','🔗 একই শব্দ অনুসন্ধান'],['translation','📝 অনুবাদ গবেষণা']];
let mode='general',speaker=true,recognition=null,listening=false,sending=false,activeController=null,lastQuestion='';
window.AL_QURAN_CHAT_API='https://al-quran-research.mosharroff0000.workers.dev/';
function getChat(){return document.getElementById('chat')||document.querySelector('.chat')}
function registerTools(){const E=window.AlQuranToolEngine;if(!E)return;const labels=Object.fromEntries(modes);modes.forEach(([id,label])=>E.register({id:'quran-'+id,name:label.replace(/^\S+\s*/,''),version:'1.0',status:'active',capabilities:[id,'chat'],permissions:[],description:'চ্যাটের '+labels[id]+' capability।'}));E.register({id:'universal-controller',name:'Universal Controller',version:'1.0',status:'active',capabilities:['tool-discovery','tool-registration','tool-execution','workspace-routing','version-aware-control'],permissions:['execution'],description:'স্বাভাবিক ভাষার অনুরোধ থেকে উপযুক্ত research capability বাছাইয়ের controller ভিত্তি।'});E.register({id:'backup-restore-controller',name:'Backup & Restore Controller',version:'1.0',status:'active',capabilities:['backup','restore','history','safe-point'],permissions:['write'],description:'নিরাপদ version/backup point-এর controller ভিত্তি।'})}
function loadToolEngine(){if(window.AlQuranToolEngine||document.getElementById('aq-tool-engine'))return true;const s=document.createElement('script');s.id='aq-tool-engine';s.src='tool-engine.js?v=20260910-1';s.onload=watch;s.onerror=setup;document.head.appendChild(s);return false}
function addStyles(){if(document.getElementById('aq-chat-v28-style'))return;const s=document.createElement('style');s.id='aq-chat-v28-style';s.textContent='.aq-modebar{display:flex;gap:7px;overflow:auto;padding:8px 15px 2px;background:#f0eee9;scrollbar-width:none}.aq-modebar::-webkit-scrollbar{display:none}.aq-mode{white-space:nowrap;border:1px solid #d2cbbc;background:#fff;border-radius:18px;padding:8px 11px;font:inherit;font-size:12px}.aq-mode.active{background:#0d5548;color:#fff;border-color:#0d5548}.aq-tools{display:flex;gap:6px;align-items:center}.aq-tool{width:43px;height:43px;border:1px solid #c9c4b8;background:#fff;border-radius:12px;font-size:19px}.aq-tool.active{background:#e8e0c8}.aq-status{font-size:11px;color:#6a645c;text-align:center;padding:4px 12px}.aq-error{display:flex;gap:6px;margin-top:5px}.aq-error button{border:1px solid #d2cbbc;background:#fff;border-radius:10px;padding:5px 9px;font:inherit;font-size:11px}.chat .composer{pointer-events:auto!important;z-index:100001!important}.chat .composer .send{pointer-events:auto!important;cursor:pointer!important;touch-action:manipulation!important}.aq-tool:disabled,.chat .composer .send:disabled{opacity:.45;cursor:wait}';document.head.appendChild(s)}
function addUser(t){const body=getChat()?.querySelector('.chat-body');if(!body)return;const d=document.createElement('div');d.className='bubble user-msg';d.textContent=t;body.appendChild(d);body.scrollTop=body.scrollHeight}
function addAI(t,speak=true,retry=false){const body=getChat()?.querySelector('.chat-body');if(!body)return;const row=document.createElement('div');row.className='ai-row';const b=document.createElement('div');b.className='bubble ai-msg';b.textContent=t;row.appendChild(b);if(retry){const a=document.createElement('div');a.className='aq-error';const r=document.createElement('button');r.type='button';r.textContent='↻ আবার চেষ্টা';r.onclick=()=>sendMessage(lastQuestion);a.appendChild(r);row.appendChild(a)}body.appendChild(row);body.scrollTop=body.scrollHeight;if(speak&&speaker)say(t)}
function say(t){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='bn-BD';u.rate=.92;u.pitch=1;window.speechSynthesis.speak(u)}
function stopSpeaking(){if('speechSynthesis' in window)window.speechSynthesis.cancel()}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){addAI('আপনার ব্রাউজারে বাংলা ভয়েস ইনপুট সুবিধা নেই। Chrome-এ চেষ্টা করুন।',false);return}if(listening){recognition?.stop();return}recognition=new SR();recognition.lang='bn-BD';recognition.interimResults=false;recognition.maxAlternatives=1;listening=true;const st=document.getElementById('aq-status'),mic=document.getElementById('aq-mic');if(st)st.textContent='🎙️ শুনছি… বাংলায় বলুন';if(mic)mic.textContent='⏹️';recognition.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript?.trim();const input=document.getElementById('aq-input');if(input&&text){input.value=text;sendMessage()}};recognition.onerror=()=>addAI('ভয়েস শুনতে সমস্যা হয়েছে। আবার 🎤 চাপুন।',false);recognition.onend=()=>{listening=false;if(st)st.textContent='বাংলা ভয়েস ও স্পিকার প্রস্তুত';if(mic)mic.textContent='🎤'};try{recognition.start()}catch(e){listening=false}}
function setup(){addStyles();registerTools();const chat=getChat();if(!chat)return false;const body=chat.querySelector('.chat-body');if(!body)return false;if(!document.getElementById('aq-modebar')){const bar=document.createElement('div');bar.id='aq-modebar';bar.className='aq-modebar';modes.forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.className='aq-mode'+(id===mode?' active':'');b.dataset.mode=id;b.textContent=label;b.setAttribute('aria-label',label);b.onclick=()=>{mode=id;bar.querySelectorAll('.aq-mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));addAI('মোড পরিবর্তন হয়েছে: '+label+'। এখন আপনার প্রশ্ন বলুন বা লিখুন।',false)};bar.appendChild(b)});body.parentNode.insertBefore(bar,body)}const composer=chat.querySelector('.composer');if(!composer)return true;let tools=composer.querySelector('.aq-tools');if(!tools){tools=document.createElement('div');tools.className='aq-tools';const mic=document.createElement('button');mic.id='aq-mic';mic.className='aq-tool';mic.title='বাংলায় কথা বলুন';mic.setAttribute('aria-label','বাংলায় কথা বলুন');mic.textContent='🎤';mic.type='button';mic.onclick=startVoice;const sp=document.createElement('button');sp.id='aq-speaker';sp.className='aq-tool active';sp.title='উত্তর শুনুন';sp.setAttribute('aria-label','উত্তর শুনুন');sp.textContent='🔊';sp.type='button';sp.onclick=()=>{speaker=!speaker;sp.classList.toggle('active',speaker);sp.textContent=speaker?'🔊':'🔇';if(!speaker)stopSpeaking()};tools.append(mic,sp);composer.insertBefore(tools,composer.firstChild)}const input=composer.querySelector('input,textarea');const send=composer.querySelector('.send,button[type="submit"]');if(input){input.id='aq-input';input.placeholder='বাংলায় লিখুন বা 🎤 চাপুন...';input.setAttribute('aria-label','বাংলায় প্রশ্ন লিখুন');input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}}if(send){send.id='aq-send';send.type='button';send.onclick=e=>{e.preventDefault();e.stopPropagation();sendMessage()};send.ontouchend=e=>{e.preventDefault();sendMessage()}}if(!document.getElementById('aq-status')){const st=document.createElement('div');st.id='aq-status';st.className='aq-status';st.textContent='বাংলা ভয়েস ও স্পিকার প্রস্তুত';composer.parentNode.insertBefore(st,composer)}return true}
async function sendMessage(override){if(sending)return;const input=document.getElementById('aq-input');if(!input)return;const text=String(override??input.value??'').trim();if(!text)return;lastQuestion=text;sending=true;const send=document.getElementById('aq-send');if(send)send.disabled=true;input.value='';addUser(text);const st=document.getElementById('aq-status');if(st)st.textContent='উত্তর তৈরি হচ্ছে…';activeController=new AbortController();const timeout=setTimeout(()=>activeController?.abort(),30000);try{const r=await fetch(window.AL_QURAN_CHAT_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,mode:mode,language:'bn'}),signal:activeController.signal});const raw=await r.text();let data={};try{data=JSON.parse(raw)}catch(_){}if(!r.ok)throw new Error(data?.detail||data?.error||('Worker HTTP '+r.status));if(!data.answer)throw new Error('Worker থেকে উত্তর আসেনি।');addAI(data.answer);if(st)st.textContent='বাংলা AI চ্যাট প্রস্তুত'}catch(e){if(e?.name==='AbortError'){addAI('বর্তমান AI উত্তর তৈরির কাজ থামানো হয়েছে। চাইলে আবার চেষ্টা করুন।',false,true);if(st)st.textContent='AI উত্তর থামানো হয়েছে'}else{console.error('AI chat error:',e);addAI('AI সংযোগে সমস্যা হয়েছে। স্থানীয় গবেষণা সহকারী সক্রিয় হয়েছে।\n\n'+localAnswer(text,mode),false,true);if(st)st.textContent='স্থানীয় সহকারী সক্রিয়'}}finally{clearTimeout(timeout);activeController=null;sending=false;if(send)send.disabled=false}}
function cancel(){if(activeController)activeController.abort();else stopSpeaking()}
function clearChat(){const body=getChat()?.querySelector('.chat-body');if(body)body.innerHTML='';const st=document.getElementById('aq-status');if(st)st.textContent='চ্যাট পরিষ্কার হয়েছে';lastQuestion='';stopSpeaking()}
function localAnswer(q,m){if(m==='math'||/গাণিতিক|হিসাব|কতবার|সংখ্যা|শতকরা|অনুপাত/.test(q))return 'গাণিতিক গবেষণা মোড চালু আছে। যাচাইকৃত ডেটা ছাড়া কোনো সংখ্যা অনুমান করা হবে না।';if(m==='word')return 'শব্দ গবেষণা মোড চালু আছে। শব্দ দিলে Root/ধাতু, Lemma, Morphology, সম্ভাব্য অর্থপরিসর ও ব্যবহার গবেষণার কাঠামো সক্রিয় থাকবে।';if(m==='ayah')return 'আয়াত বিশ্লেষণ মোড চালু আছে। সূরা ও আয়াত নম্বর দিলে ভাষা, শব্দ, ব্যাকরণ ও প্রসঙ্গভিত্তিক গবেষণার কাঠামো ব্যবহার করা হবে।';if(m==='concordance')return 'একই শব্দ অনুসন্ধান মোড চালু আছে। নির্দিষ্ট শব্দের বিভিন্ন অবস্থান ও ব্যবহার একত্র করার কাঠামো সক্রিয় আছে।';if(m==='translation')return 'অনুবাদ গবেষণা মোড চালু আছে। মূল শব্দের অর্থপরিসর, বাক্য-প্রসঙ্গ ও বাংলা রূপ আলাদা করে দেখা হবে।';return 'আল-কুরআন গবেষণা সহকারী প্রস্তুত। বাংলায় প্রশ্ন লিখুন অথবা 🎤 চাপ দিয়ে বাংলায় কথা বলুন। 🔊 চালু থাকলে উত্তর পড়ে শোনানো হবে।'}
function watch(){if(!window.AlQuranToolEngine&&!loadToolEngine())return;if(!setup())setTimeout(watch,300)}
window.AlQuranChat={setup,sendMessage,startVoice,say,cancel,clearChat,getMode:()=>mode,getTools:()=>window.AlQuranToolEngine?.list?.()||[]};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();
