/* আল-কুরআন গবেষণা — চ্যাট সিস্টেম v2.5
   পুরোনো ভয়েস + স্পিকার + মোড + স্থানীয় fallback বজায় রাখা হয়েছে।
   Worker URL: Cloudflare deployment-এর প্রকৃত URL।
*/
(function(){
'use strict';
const modes=[['general','💬 সাধারণ প্রশ্ন'],['word','🔎 শব্দ গবেষণা'],['ayah','🧩 আয়াত বিশ্লেষণ'],['math','📊 গাণিতিক গবেষণা'],['concordance','🔗 একই শব্দ অনুসন্ধান'],['translation','📝 অনুবাদ গবেষণা']];
let mode='general', speaker=true, recognition=null, listening=false, sending=false;
window.AL_QURAN_CHAT_API='https://al-quran-research.mosharrof0000.workers.dev/';
function getChat(){return document.getElementById('chat')||document.querySelector('.chat')}
function addStyles(){if(document.getElementById('aq-chat-v25-style'))return;const s=document.createElement('style');s.id='aq-chat-v25-style';s.textContent='.aq-modebar{display:flex;gap:7px;overflow:auto;padding:8px 15px 2px;background:#f0eee9;scrollbar-width:none}.aq-modebar::-webkit-scrollbar{display:none}.aq-mode{white-space:nowrap;border:1px solid #d2cbbc;background:#fff;border-radius:18px;padding:8px 11px;font:inherit;font-size:12px}.aq-mode.active{background:#0d5548;color:#fff;border-color:#0d5548}.aq-tools{display:flex;gap:6px;align-items:center}.aq-tool{width:43px;height:43px;border:1px solid #c9c4b8;background:#fff;border-radius:12px;font-size:19px}.aq-tool.active{background:#e8e0c8}.aq-status{font-size:11px;color:#6a645c;text-align:center;padding:4px 12px}.chat .composer{pointer-events:auto!important;z-index:100001!important}.chat .composer .send{pointer-events:auto!important;cursor:pointer!important;touch-action:manipulation!important}';document.head.appendChild(s)}
function addUser(t){const body=getChat()?.querySelector('.chat-body');if(!body)return;const d=document.createElement('div');d.className='bubble user-msg';d.textContent=t;body.appendChild(d);body.scrollTop=body.scrollHeight}
function addAI(t,speak=true){const body=getChat()?.querySelector('.chat-body');if(!body)return;const row=document.createElement('div');row.className='ai-row';const b=document.createElement('div');b.className='bubble ai-msg';b.textContent=t;row.appendChild(b);body.appendChild(row);body.scrollTop=body.scrollHeight;if(speak&&speaker)say(t)}
function say(t){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='bn-BD';u.rate=.92;u.pitch=1;window.speechSynthesis.speak(u)}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){addAI('আপনার ব্রাউজারে বাংলা ভয়েস ইনপুট সুবিধা নেই। Chrome-এ চেষ্টা করুন।',false);return}if(listening){recognition?.stop();return}recognition=new SR();recognition.lang='bn-BD';recognition.interimResults=false;recognition.maxAlternatives=1;listening=true;const st=document.getElementById('aq-status'),mic=document.getElementById('aq-mic');if(st)st.textContent='🎙️ শুনছি… বাংলায় বলুন';if(mic)mic.textContent='⏹️';recognition.onresult=e=>{const text=e.results[0][0].transcript;const input=document.getElementById('aq-input');if(input){input.value=text;sendMessage()}};recognition.onerror=()=>addAI('ভয়েস শুনতে সমস্যা হয়েছে। আবার 🎤 চাপুন।',false);recognition.onend=()=>{listening=false;if(st)st.textContent='বাংলা ভয়েস ও স্পিকার প্রস্তুত';if(mic)mic.textContent='🎤'};recognition.start()}
function setup(){addStyles();const chat=getChat();if(!chat)return false;const body=chat.querySelector('.chat-body');if(!body)return false;if(!document.getElementById('aq-modebar')){const bar=document.createElement('div');bar.id='aq-modebar';bar.className='aq-modebar';modes.forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.className='aq-mode'+(id===mode?' active':'');b.dataset.mode=id;b.textContent=label;b.onclick=()=>{mode=id;bar.querySelectorAll('.aq-mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));addAI('মোড পরিবর্তন হয়েছে: '+label+'। এখন আপনার প্রশ্ন বলুন বা লিখুন।',false)};bar.appendChild(b)});body.parentNode.insertBefore(bar,body)}const composer=chat.querySelector('.composer');if(!composer)return true;let tools=composer.querySelector('.aq-tools');if(!tools){tools=document.createElement('div');tools.className='aq-tools';const mic=document.createElement('button');mic.id='aq-mic';mic.className='aq-tool';mic.title='বাংলায় কথা বলুন';mic.textContent='🎤';mic.type='button';mic.onclick=startVoice;const sp=document.createElement('button');sp.id='aq-speaker';sp.className='aq-tool active';sp.title='উত্তর শুনুন';sp.textContent='🔊';sp.type='button';sp.onclick=()=>{speaker=!speaker;sp.classList.toggle('active',speaker);sp.textContent=speaker?'🔊':'🔇'};tools.append(mic,sp);composer.insertBefore(tools,composer.firstChild)}const input=composer.querySelector('input');const send=composer.querySelector('.send');if(input){input.id='aq-input';input.placeholder='বাংলায় লিখুন বা 🎤 চাপুন...';input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendMessage()}}}if(send){send.id='aq-send';send.type='button';send.onclick=e=>{e.preventDefault();e.stopPropagation();sendMessage()};send.ontouchend=e=>{e.preventDefault();sendMessage()}}if(!document.getElementById('aq-status')){const st=document.createElement('div');st.id='aq-status';st.className='aq-status';st.textContent='বাংলা ভয়েস ও স্পিকার প্রস্তুত';composer.parentNode.insertBefore(st,composer)}return true}
async function sendMessage(){if(sending)return;const input=document.getElementById('aq-input');if(!input)return;const text=input.value.trim();if(!text)return;sending=true;const send=document.getElementById('aq-send');if(send)send.disabled=true;input.value='';addUser(text);const st=document.getElementById('aq-status');if(st)st.textContent='উত্তর তৈরি হচ্ছে…';try{const r=await fetch(window.AL_QURAN_CHAT_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,mode:mode,language:'bn'})});const raw=await r.text();let data={};try{data=JSON.parse(raw)}catch(_){}if(!r.ok)throw new Error(data?.detail||data?.error||('Worker HTTP '+r.status));if(!data.answer)throw new Error('Worker থেকে উত্তর আসেনি।');addAI(data.answer);if(st)st.textContent='বাংলা AI চ্যাট প্রস্তুত'}catch(e){console.error('AI chat error:',e);addAI('AI সংযোগে সমস্যা হয়েছে। এখন স্থানীয় গবেষণা সহকারী উত্তর দিচ্ছে।\n\n'+localAnswer(text,mode),false);if(st)st.textContent='স্থানীয় সহকারী সক্রিয়'}finally{sending=false;if(send)send.disabled=false}}
function localAnswer(q,m){if(m==='math'||/গাণিতিক|হিসাব|কতবার|সংখ্যা|শতকরা|অনুপাত/.test(q))return 'গাণিতিক গবেষণা মোড চালু আছে। সম্পূর্ণ কুরআন ডেটাবেস যুক্ত হলে শব্দ, আয়াত, সূরা, পুনরাবৃত্তি, অনুপাত ও সূত্রভিত্তিক হিসাব ডেটা থেকে করা হবে। এখন কোনো সংখ্যা অনুমান করা হবে না।';if(m==='word')return 'শব্দ গবেষণা মোড চালু আছে। একটি শব্দ দিলে মূল/ধাতু, শব্দরূপ, সম্ভাব্য অর্থপরিসর ও ব্যবহার খোঁজার কাঠামো ব্যবহার করা হবে।';if(m==='ayah')return 'আয়াত বিশ্লেষণ মোড চালু আছে। সূরা ও আয়াত নম্বর দিলে ভাষা, শব্দ, ব্যাকরণ ও প্রসঙ্গভিত্তিক গবেষণা করা হবে।';if(m==='concordance')return 'একই শব্দ অনুসন্ধান মোড চালু আছে। নির্দিষ্ট শব্দ দিলে তার বিভিন্ন অবস্থান ও ব্যবহার একত্র করা হবে।';if(m==='translation')return 'অনুবাদ গবেষণা মোড চালু আছে। মূল শব্দের অর্থপরিসর, বাক্য-প্রসঙ্গ এবং বাংলা রূপ আলাদা করে দেখা হবে।';return 'আল-কুরআন গবেষণা সহকারী প্রস্তুত। বাংলায় প্রশ্ন লিখুন অথবা 🎤 চাপ দিয়ে বাংলায় কথা বলুন। 🔊 চালু থাকলে উত্তর পড়ে শোনানো হবে।'}
function watch(){if(!setup())setTimeout(watch,300)}
window.AlQuranChat={setup,sendMessage,startVoice,say};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();