/* আল-কুরআন গবেষণা — চ্যাট সিস্টেম v2
   নিরাপত্তা: API key এখানে রাখা হবে না।
   Cloudflare Worker endpoint সংযুক্ত করা হয়েছে।
*/
(function(){
'use strict';
window.AL_QURAN_CHAT_API='https://al-quran-research.mosharrof0000.workers.dev/';
let mode='general',speaker=true;
const modes=[['general','💬 সাধারণ প্রশ্ন'],['word','🔎 শব্দ গবেষণা'],['ayah','🧩 আয়াত বিশ্লেষণ'],['math','📊 গাণিতিক গবেষণা'],['concordance','🔗 একই শব্দ অনুসন্ধান'],['translation','📝 অনুবাদ গবেষণা']];
function getChat(){return document.getElementById('chat')}
function addStyles(){if(document.getElementById('aq-chat-fix-style'))return;const s=document.createElement('style');s.id='aq-chat-fix-style';s.textContent='.chat .composer{pointer-events:auto!important;z-index:100001!important}.chat .composer .send{pointer-events:auto!important;cursor:pointer!important;touch-action:manipulation!important}.aq-modebar{display:flex;gap:7px;overflow:auto;padding:8px 15px 2px;background:#f0eee9}.aq-mode{white-space:nowrap;border:1px solid #d2cbbc;background:#fff;border-radius:18px;padding:8px 11px;font:inherit;font-size:12px}.aq-mode.active{background:#0d5548;color:#fff}.aq-status{font-size:11px;color:#6a645c;text-align:center;padding:4px 12px}';document.head.appendChild(s)}
function addUser(t){const b=getChat()?.querySelector('.chat-body');if(!b)return;const d=document.createElement('div');d.className='bubble user-msg';d.textContent=t;b.appendChild(d);d.scrollIntoView({behavior:'smooth',block:'nearest'})}
function say(t){if(!speaker||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='bn-BD';u.rate=.92;speechSynthesis.speak(u)}
function addAI(t,s=true){const b=getChat()?.querySelector('.chat-body');if(!b)return;const r=document.createElement('div');r.className='ai-row';const d=document.createElement('div');d.className='bubble ai-msg';d.textContent=t;r.appendChild(d);b.appendChild(r);r.scrollIntoView({behavior:'smooth',block:'nearest'});if(s)say(t)}
function ensureComposer(){const chat=getChat();if(!chat)return null;let c=chat.querySelector('.composer');if(!c){c=document.createElement('div');c.className='composer';c.innerHTML='<input id="aq-input" type="text" placeholder="বাংলায় প্রশ্ন লিখুন..."><button id="aq-send" class="send" type="button">➤</button>';chat.appendChild(c)}const input=c.querySelector('input');const send=c.querySelector('.send');if(input){input.id='aq-input';input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendMessage()}}}if(send){send.id='aq-send';send.onclick=e=>{e.preventDefault();e.stopPropagation();sendMessage()};send.ontouchend=e=>{e.preventDefault();sendMessage()}}return c}
function setup(){addStyles();const chat=getChat();if(!chat)return false;const body=chat.querySelector('.chat-body');if(!body)return false;if(!document.getElementById('aq-modebar')){const bar=document.createElement('div');bar.id='aq-modebar';bar.className='aq-modebar';modes.forEach(x=>{const b=document.createElement('button');b.className='aq-mode'+(x[0]===mode?' active':'');b.textContent=x[1];b.onclick=()=>{mode=x[0];bar.querySelectorAll('.aq-mode').forEach(q=>q.classList.toggle('active',q===b));addAI('মোড পরিবর্তন হয়েছে। এখন আপনার প্রশ্ন লিখুন।',false)};bar.appendChild(b)});body.parentNode.insertBefore(bar,body)}ensureComposer();return true}
async function sendMessage(){const input=document.getElementById('aq-input');if(!input)return;const text=input.value.trim();if(!text)return;input.value='';addUser(text);const status=document.getElementById('aq-status');if(status)status.textContent='উত্তর তৈরি হচ্ছে…';try{const r=await fetch(window.AL_QURAN_CHAT_API,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({message:text,mode:mode,language:'bn'})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.detail||data?.error||('Worker HTTP '+r.status));if(!data.answer)throw new Error('Worker থেকে উত্তর আসেনি।');addAI(data.answer);if(status)status.textContent='বাংলা AI চ্যাট প্রস্তুত';}catch(e){console.error(e);addAI('AI সংযোগে সমস্যা হয়েছে।\nকারণ: '+(e?.message||e),false);if(status)status.textContent='আবার চেষ্টা করুন';}}
function openChat(){const c=getChat();if(!c)return false;document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));c.classList.add('active');setup();setTimeout(()=>document.getElementById('aq-input')?.focus(),100);return true}
window.AlQuranChat={setup,sendMessage,openChat};
function init(){addStyles();setup();document.addEventListener('click',e=>{const b=e.target.closest?.('.send');if(b&&getChat()?.classList.contains('active')){e.preventDefault();e.stopPropagation();sendMessage()}},{capture:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();