/* Al-Quran Research — Project Agent Engine v2
   Identity + task/session ledger + isolated per-task branch.
   NEVER merges or deploys. Production remains untouched.
*/
const ALLOWED_ORIGINS=['https://mosharrof0000-ux.github.io'];
const API='https://api.github.com';
const DEFAULT_REPO='mosharrof0000-ux/al-quran-research';
const MAX_FILE=120000, MAX_TURNS=10;

function cors(origin){return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.includes(origin)?origin:ALLOWED_ORIGINS[0],'Access-Control-Allow-Methods':'POST, GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};}
function json(data,status,origin){return new Response(JSON.stringify(data),{status,headers:cors(origin)});}
function repo(env){return env.PROJECT_REPO||DEFAULT_REPO;}
function safeBranch(b){return /^agent\\/[A-Za-z0-9._/-]+$/.test(String(b||''))&&!String(b).includes('..');}
function safePath(path,write=false){const p=String(path||'').replace(/^\\/+?/,'');if(!p||p.includes('..')||p.startsWith('.git/'))return false;if(write){const blocked=['.github/','database/','migrations/','validation/'];if(blocked.some(x=>p.startsWith(x))||['quran_research.db','schema.sql'].includes(p))return false;}return true;}
async function gh(env,path,init={}){if(!env.GITHUB_TOKEN)throw new Error('GITHUB_TOKEN is not configured.');const r=await fetch(API+path,{...init,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+env.GITHUB_TOKEN,'X-GitHub-Api-Version':'2026-03-10','User-Agent':'al-quran-research-project-agent',...(init.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error('GitHub HTTP '+r.status+': '+String(d?.message||t).slice(0,500));return d;}
function classify(m){const s=m.toLowerCase();if(/icon|আইকন/.test(s))return ['শাহীন','ICON'];if(/reader|কুরআন পাঠ|রিডার|আয়াত|আয়াত/.test(s))return ['সুমন','READER'];if(/font|ফন্ট|typography|টেক্সট/.test(s))return ['রাকিব','FONT'];if(/chat|চ্যাট|ai|এআই|agent|এজেন্ট/.test(s))return ['নাঈম','AI'];if(/test|browser|visual|পরীক্ষা|যাচাই/.test(s))return ['তানভীর','TEST'];return ['আরিফ','GENERAL'];}
function slugName(n){return ({'শাহীন':'shahin','সুমন':'sumon','রাকিব':'rakib','নাঈম':'naim','তানভীর':'tanvir','আরিফ':'arif'})[n]||'agent';}
function makeIdentity(message){const [name,type]=classify(message);const stamp=new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14);const rand=crypto.randomUUID().slice(0,6);const taskId='AGENT-'+stamp+'-'+rand.toUpperCase();const agentId=slugName(name).toUpperCase()+'-AGENT-'+stamp+'-'+rand.toUpperCase();const sessionId='SESSION-'+crypto.randomUUID().toUpperCase();const branch='agent/'+slugName(name)+'-'+type.toLowerCase()+'-'+stamp+'-'+rand;return {name,type,taskId,agentId,sessionId,branch};}
async function createBranch(env,branch){const ref=await gh(env,'/repos/'+repo(env)+'/git/ref/heads/main');await gh(env,'/repos/'+repo(env)+'/git/refs',{method:'POST',body:JSON.stringify({ref:'refs/heads/'+branch,sha:ref.object.sha}),headers:{'Content-Type':'application/json'}});return ref.object.sha;}
async function readFile(env,args){const path=String(args.path||''),branch=String(args.branch||'main');if(!safePath(path))throw new Error('এই path অনুমোদিত নয়।');const d=await gh(env,'/repos/'+repo(env)+'/contents/'+path.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(branch));if(d.type!=='file')throw new Error('এটি file নয়।');if(Number(d.size||0)>MAX_FILE)throw new Error('ফাইলটি engine সীমার চেয়ে বড়।');const bin=atob(String(d.content||'').replace(/\\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return {path,branch,sha:d.sha,size:d.size,content:new TextDecoder().decode(bytes)};}
async function listDir(env,args){const path=String(args.path||''),branch=String(args.branch||'main');if(!safePath(path))throw new Error('এই path অনুমোদিত নয়।');const d=await gh(env,'/repos/'+repo(env)+'/contents/'+path.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(branch));if(!Array.isArray(d))throw new Error('Directory পাওয়া যায়নি।');return d.map(x=>({name:x.name,path:x.path,type:x.type,size:x.size||0}));}
async function searchCode(env,args){const q=String(args.query||'').trim();if(!q)throw new Error('search query প্রয়োজন।');const d=await gh(env,'/search/code?q='+encodeURIComponent(q+' repo:'+repo(env)));return (d.items||[]).slice(0,20).map(x=>({path:x.path,html_url:x.html_url}));}
async function writeFile(env,args){const path=String(args.path||''),branch=String(args.branch||'');if(!safeBranch(branch))throw new Error('শুধু agent/* branch-এ write করা যাবে।');if(!safePath(path,true))throw new Error('protected path।');const content=String(args.content||'');if(content.length>MAX_FILE)throw new Error('ফাইলটি engine সীমার চেয়ে বড়।');let old=null;try{old=await gh(env,'/repos/'+repo(env)+'/contents/'+path.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(branch))}catch{}const payload={message:String(args.message||'AI agent change'),content:btoa(unescape(encodeURIComponent(content))),branch};if(old?.sha)payload.sha=old.sha;const d=await gh(env,'/repos/'+repo(env)+'/contents/'+path.split('/').map(encodeURIComponent).join('/'),{method:'PUT',body:JSON.stringify(payload),headers:{'Content-Type':'application/json'}});return {path,branch,commit_sha:d.commit?.sha||null};}
async function record(env,id,branch,base,meta,status,answer,changed){const path='docs/agent-tasks/'+id+'.md';const body='# Agent Task Record\\n\\n- Task ID: '+id+'\\n- Agent Name: '+meta.name+'\\n- Agent ID: '+meta.agentId+'\\n- Session ID: '+meta.sessionId+'\\n- Work Type: '+meta.type+'\\n- Request: '+meta.request.replace(/\\n/g,' ')+'\\n- Status: '+status+'\\n- Branch: '+branch+'\\n- Base: '+base+'\\n- Changed files reported by Agent: '+(changed.length?changed.join(', '):'none reported')+'\\n- Merge: NO\\n- Production deploy: NO\\n- Live verification: PENDING\\n- Agent result: '+answer.slice(0,6000)+'\\n- Created: '+new Date().toISOString()+'\\n';return writeFile(env,{path,branch,content:body,message:'Record '+id+' work history'});}
const TOOLS=[{name:'project_read_file',description:'Read a project file before changing it.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},{name:'project_list_directory',description:'List a project directory.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},{name:'project_search_code',description:'Search project code.',parameters:{type:'object',properties:{query:{type:'string'}},required:['query']}},{name:'project_write_file',description:'Create or replace a text file only on the assigned agent branch; never protected paths.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'},content:{type:'string'},message:{type:'string'}},required:['path','branch','content','message']}}];
async function tool(env,n,a){if(n==='project_read_file')return readFile(env,a);if(n==='project_list_directory')return listDir(env,a);if(n==='project_search_code')return searchCode(env,a);if(n==='project_write_file')return writeFile(env,a);throw new Error('Unknown tool');}
async function runGemini(env,message,meta){if(!env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY is not configured.');const model=env.GEMINI_MODEL||'gemini-2.5-flash';const system='তুমি Project Agent '+meta.name+'। Agent ID '+meta.agentId+'; Task ID '+meta.taskId+'; Session ID '+meta.sessionId+'। এই কাজের branch হলো '+meta.branch+'। প্রথমে project inspect করবে, তারপর প্রয়োজনীয় minimal change করবে। main-এ কখনো লিখবে না। .github/workflows, database, migrations, validation, quran_research.db, schema.sql protected। শুধু assigned agent branch ব্যবহার করবে। অনুমান নয়; source/context পড়ে কাজ করবে। কাজ শেষে পড়া/পরিবর্তিত file, tests, remaining work এবং approval/deploy status স্পষ্টভাবে বলবে। merge/deploy করতে পারবে না।';let c=[{role:'user',parts:[{text:message+'\\n\\nSystem-assigned identity: '+JSON.stringify(meta)}]}];for(let turn=0;turn<MAX_TURNS;turn++){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:c,tools:[{functionDeclarations:TOOLS}],generationConfig:{maxOutputTokens:5000,temperature:0.1}})});const d=await r.json();if(!r.ok)throw new Error('Gemini HTTP '+r.status+': '+String(d?.error?.message||'').slice(0,500));const mc=d?.candidates?.[0]?.content;if(!mc)throw new Error('Gemini response missing content.');const calls=(mc.parts||[]).filter(p=>p.functionCall);if(!calls.length)return {answer:(mc.parts||[]).map(p=>p.text||'').join('').trim(),model};c.push(mc);const rs=[];for(const p of calls){let out;try{out=await tool(env,p.functionCall.name,p.functionCall.args||{})}catch(e){out={ok:false,error:String(e?.message||e)}}rs.push({functionResponse:{name:p.functionCall.name,response:{result:out}}});}c.push({role:'user',parts:rs});}throw new Error('Agent tool loop limit reached.');}
export default {async fetch(request,env){const origin=request.headers.get('Origin')||'';if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(request.method==='GET')return json({ok:true,service:'al-quran-research-project-agent',version:env.AGENT_VERSION||'2.0.0',identity:true,task_ledger:true,isolated:true,merge:false,deploy:false},200,origin);if(request.method!=='POST')return json({ok:false,error:'POST/GET only'},405,origin);const auth=request.headers.get('Authorization')||'';if(!env.AGENT_ACCESS_TOKEN||auth!=='Bearer '+env.AGENT_ACCESS_TOKEN)return json({ok:false,error:'Unauthorized'},401,origin);try{const b=await request.json(),message=String(b?.message||'').trim();if(!message)return json({ok:false,error:'message required'},400,origin);if(message.length>10000)return json({ok:false,error:'message too large'},413,origin);const meta=makeIdentity(message);meta.request=message;const base=await createBranch(env,meta.branch);let result;try{result=await runGemini(env,message,meta);}catch(e){result={answer:'Agent execution failed: '+String(e?.message||e),model:null};}const status=result.answer.startsWith('Agent execution failed:')?'BLOCKED':'WORKING';const changed=[];const rec=await record(env,meta.taskId,meta.branch,base,meta,status,result.answer,changed);return json({ok:status!=='BLOCKED',answer:result.answer,agent_name:meta.name,agent_id:meta.agentId,task_id:meta.taskId,session_id:meta.sessionId,branch:meta.branch,ledger_record:rec.path,provider:result.model,version:env.AGENT_VERSION||'2.0.0',isolated:true,merge:false,deploy:false},status==='BLOCKED'?500:200,origin);}catch(e){return json({ok:false,error:'PROJECT_AGENT_FAILED',detail:String(e?.message||e).slice(0,700)},500,origin);}}};