/* Project Agent Engine v2 — isolated autonomous task runner */
const API='https://api.github.com', REPO='mosharrof0000-ux/al-quran-research';
const ORIGIN='https://mosharrof0000-ux.github.io', MAX_FILE=120000, MAX_TURNS=12, MAX_MESSAGE=10000, GEMINI_TIMEOUT_MS=45000;
const PEOPLE=[
 ['শাহীন','shahin',['agent','system','engine','architecture','workflow','ai']],
 ['শামীম','shamim',['chat','চ্যাট','ui','interface','header','input']],
 ['সুমন','sumon',['reader','কুরআন','quran','আয়াত','সূরা','translation','pronunciation']],
 ['নাঈম','naim',['test','browser','visual','console','network','verification']],
 ['রাকিব','rakib',['notification','notify','update','version','live']],
 ['ফারহান','farhan',['data','database','dataset','mapping','schema']],
 ['রিয়াদ','riyad',['icon','icons','asset','font','typography']],
 ['তানভীর','tanvir',['security','token','auth','permission','safety']]
];
const headers=o=>({'Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Content-Type':'application/json; charset=utf-8',...o});
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:headers()});
const agentBranch=b=>/^agent\/[A-Za-z0-9._/-]+$/.test(b)&&!b.includes('..');
const safe=(p,w=false)=>{p=String(p||'').replace(/^\/+/, '');if(!p||p.includes('..')||p.startsWith('.git/'))return false;if(w&&( ['.github/','database/','migrations/','validation/'].some(x=>p.startsWith(x))||['quran_research.db','schema.sql'].includes(p)||/(^|[\\/])(?:\.env|secrets?|credentials?)(?:[\\/]|$)/i.test(p)))return false;return true};
const b64=s=>{const a=new TextEncoder().encode(s);let z='';for(let i=0;i<a.length;i+=32768)z+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(z)};
async function gh(env,path,init={}){if(!env.GITHUB_TOKEN)throw Error('GITHUB_TOKEN is not configured.');const r=await fetch(API+path,{...init,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+env.GITHUB_TOKEN,'X-GitHub-Api-Version':'2026-03-10','User-Agent':'al-quran-research-project-agent',...(init.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={message:t}}if(!r.ok)throw Error('GitHub HTTP '+r.status+': '+String(d.message||t).slice(0,500));return d}
function taskFor(message){const m=message.toLowerCase();let best=PEOPLE[0],score=-1;for(const p of PEOPLE){const n=p[2].filter(k=>m.includes(k.toLowerCase())).length;if(n>score){score=n;best=p}}const u=crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),stamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14),id='TASK-'+stamp+'-'+u;return {taskId:id,agentName:best[0],slug:best[1],agentId:best[1].toUpperCase()+'-AGENT-'+u,sessionId:'SESSION-'+u,branch:'agent/'+best[1]+'-'+id.toLowerCase(),createdAt:new Date().toISOString(),message}}
async function makeBranch(env,b,base='main'){if(base!=='main'&&!agentBranch(base))throw Error('Invalid base branch.');const r=await gh(env,'/repos/'+REPO+'/git/ref/heads/'+encodeURIComponent(base));return gh(env,'/repos/'+REPO+'/git/refs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'refs/heads/'+b,sha:r.object.sha})})}
async function write(env,p,b,c,msg){if(!agentBranch(b)||!safe(p,true))throw Error('Agent write scope violation.');let old=null;try{old=await gh(env,'/repos/'+REPO+'/contents/'+p+'?ref='+encodeURIComponent(b))}catch{}const body={message:msg,content:b64(c),branch:b};if(old?.sha)body.sha=old.sha;const result=await gh(env,'/repos/'+REPO+'/contents/'+p,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const verified=await read(env,p,b);if(verified.content!==c)throw Error('Write verification failed.');return {...result,write_verified:true}}
async function read(env,p,b='main'){if(!safe(p))throw Error('Invalid path.');const d=await gh(env,'/repos/'+REPO+'/contents/'+p+'?ref='+encodeURIComponent(b));if(d.type!=='file'||Number(d.size||0)>MAX_FILE)throw Error('File unavailable/too large.');const x=atob(String(d.content||'').replace(/\n/g,''));return {path:p,branch:b,sha:d.sha,content:new TextDecoder().decode(Uint8Array.from(x,c=>c.charCodeAt(0)))}}
async function list(env,p='',b='main'){if(!safe(p))throw Error('Invalid path.');const d=await gh(env,'/repos/'+REPO+'/contents/'+p+'?ref='+encodeURIComponent(b));if(!Array.isArray(d))throw Error('Directory unavailable.');return d.map(x=>({name:x.name,path:x.path,type:x.type,size:x.size||0}))}
async function search(env,q){const d=await gh(env,'/search/code?q='+encodeURIComponent(q+' repo:'+REPO));return(d.items||[]).slice(0,20).map(x=>({path:x.path,url:x.html_url}))}
async function preflight(env,b='main'){const paths=['MASTER_INSTRUCTION.md','PROJECT_STATE.md','MASTER_PROJECT.md','AI_ENTRY_PROTOCOL.md','INSTRUCTION_REGISTRY.md','docs/PROJECT_AGENT_ENGINE_V1.md','docs/AGENT_IDENTITY_REGISTRY.md','docs/AGENT_WORK_LEDGER.md','docs/AGENT_HANDOFF_PROTOCOL.md'];const files=[];for(const p of paths){try{const x=await read(env,p,b);files.push({path:p,sha:x.sha,content:x.content.slice(0,60000)})}catch(e){files.push({path:p,missing:true,error:String(e.message||e).slice(0,180)})}}return {branch:b,files}}
async function branchState(env,b){if(b!=='main'&&!agentBranch(b))throw Error('Invalid branch.');const r=await gh(env,'/repos/'+REPO+'/git/ref/heads/'+encodeURIComponent(b));return {branch:b,sha:r.object.sha}}
const TOOLS=[
 {name:'project_inspect_repo',description:'Mandatory project governance preflight before complex work.',parameters:{type:'object',properties:{branch:{type:'string'}},required:[]}},\n {name:'project_branch_state',description:'Read exact branch head for verification.',parameters:{type:'object',properties:{branch:{type:'string'}},required:[]}},\n {name:'project_read_file',description:'Read project file before editing.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},
 {name:'project_list_directory',description:'List project directory.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},
 {name:'project_search_code',description:'Search project code.',parameters:{type:'object',properties:{query:{type:'string'}},required:['query']}},
 {name:'project_write_file',description:'Write text only to the assigned agent branch; never main or protected paths.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'},content:{type:'string'},message:{type:'string'}},required:['path','branch','content','message']}}
];
async function tool(env,n,a){if(n==='project_inspect_repo')return preflight(env,a.branch||'main');if(n==='project_branch_state')return branchState(env,a.branch||'main');if(n==='project_read_file')return read(env,a.path,a.branch||'main');if(n==='project_list_directory')return list(env,a.path||'',a.branch||'main');if(n==='project_search_code')return search(env,String(a.query||''));if(n==='project_write_file')return write(env,a.path,a.branch,a.content,a.message||'Agent change');throw Error('Unknown tool '+n)}
async function ask(env,task,message){const model=env.GEMINI_MODEL||'gemini-2.5-flash',sys=`তুমি Project Agent। বাধ্যতামূলক: complex task হলে project_inspect_repo; edit-এর আগে source পড়া; write-এর পরে write_verified ফল গ্রহণ; শেষে project_branch_state দিয়ে branch head যাচাই; ব্যর্থ হলে সীমিত self-repair, তারপর BLOCKED/INCOMPLETE_HANDOFF। পরিচয়: ${task.agentName} | Agent ID ${task.agentId} | Task ${task.taskId} | Session ${task.sessionId} | Branch ${task.branch}. প্রথমে project/docs/code পড়বে, তারপর minimal safe change করবে। শুধু assigned agent branch-এ লিখবে। main, .github/workflows, database, migrations, validation, quran_research.db, schema.sql পরিবর্তন নিষিদ্ধ। কাজ শেষে পড়া/পরিবর্তন/test/remaining/handoff স্পষ্ট করবে। merge/deploy/live-success দাবি করবে না।`;let c=[{role:'user',parts:[{text:message}]}];for(let i=0;i<MAX_TURNS;i++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),GEMINI_TIMEOUT_MS);let r;try{r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:sys}]},contents:c,tools:[{functionDeclarations:TOOLS}],generationConfig:{maxOutputTokens:4096,temperature:.1}})}catch(e){throw Error(e.name==='AbortError'?'Gemini timeout.':String(e.message||e))}finally{clearTimeout(timer)}const d=await r.json();if(!r.ok)throw Error('Gemini HTTP '+r.status+': '+String(d?.error?.message||'').slice(0,500));const mc=d?.candidates?.[0]?.content;if(!mc)throw Error('Gemini response missing content');const calls=(mc.parts||[]).filter(x=>x.functionCall);if(!calls.length)return (mc.parts||[]).map(x=>x.text||'').join('').trim();c.push(mc);const rs=[];for(const x of calls){let z;try{z=await tool(env,x.functionCall.name,x.functionCall.args||{})}catch(e){z={ok:false,error:String(e.message||e)}}rs.push({functionResponse:{name:x.functionCall.name,response:{result:z}}})}c.push({role:'user',parts:rs})}throw Error('Tool loop limit reached')}
async function record(env,t,status,extra=''){const p='docs/agent-tasks/'+t.taskId+'.md';const c=`# ${t.taskId}\n\n- Agent Name: ${t.agentName}\n- Agent ID: ${t.agentId}\n- Session ID: ${t.sessionId}\n- Branch: ${t.branch}\n- Status: ${status}\n- Started: ${t.createdAt}\n- Updated: ${new Date().toISOString()}\n\n## Request\n${t.message}\n\n## Record\n${extra||'Task received; detailed work record follows from agent commits and handoff.'}\n\n## Safety\nProduction main, merge and deployment remain outside this isolated engine.\n`;return write(env,p,t.branch,c,'Record '+t.taskId+' — '+t.agentName)}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers()});if(req.method==='GET')return out({ok:true,service:'al-quran-research-project-agent',version:env.AGENT_VERSION||'2.0.0',identity:true,task_ledger:true,handoff:true,isolated:true,write_scope:'agent/* only',merge:false,deploy:false});if(req.method!=='POST')return out({ok:false,error:'POST/GET only'},405);if((req.headers.get('Authorization')||'')!=='Bearer '+env.AGENT_ACCESS_TOKEN)return out({ok:false,error:'Unauthorized'},401);let t=null;try{const body=await req.json(),message=String(body?.message||'').trim();if(!message)return out({ok:false,error:'message required'},400);if(message.length>MAX_MESSAGE)return out({ok:false,error:'message too large'},413);t=taskFor(message);const baseBranch=String(body?.base_branch||'main').trim()||'main';await makeBranch(env,t.branch,baseBranch);await record(env,t,'RECEIVED');const answer=await ask(env,t,message);await record(env,t,'WORKING','Agent response completed. Independent review, tests and promotion remain required.');return out({ok:true,answer,agent_version:env.AGENT_VERSION||'2.0.0',identity:{name:t.agentName,id:t.agentId},task:{id:t.taskId,session:t.sessionId,branch:t.branch},isolated:true,merge:false,deploy:false})}catch(e){if(t){try{await record(env,t,'INCOMPLETE_HANDOFF','Reason: '+String(e.message||e)+'\\nNext step: inspect the branch and continue with a successor Agent.')}catch{}}return out({ok:false,error:'PROJECT_AGENT_FAILED',detail:String(e.message||e).slice(0,600),identity:t?{name:t.agentName,id:t.agentId}:null,task:t?{id:t.taskId,session:t.sessionId,branch:t.branch}:null},500)}}};
