/* Al-Quran Research — Project Agent Engine v1.1 */
const ALLOWED_ORIGINS=['https://mosharrof0000-ux.github.io'];
const API='https://api.github.com', DEFAULT_REPO='mosharrof0000-ux/al-quran-research';
const MAX_FILE=120000, MAX_TURNS=10;
function cors(o){return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.includes(o)?o:ALLOWED_ORIGINS[0],'Access-Control-Allow-Methods':'POST, GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Content-Type':'application/json; charset=utf-8','Vary':'Origin'}}
function json(d,s,o){return new Response(JSON.stringify(d),{status:s,headers:cors(o)})}
function repo(e){return e.PROJECT_REPO||DEFAULT_REPO}
function isAgentBranch(b){return /^agent\/[A-Za-z0-9._/-]+$/.test(String(b||''))&&!String(b).includes('..')}
function safePath(p,w=false){p=String(p||'').replace(/^\/+/,'');if(!p||p.includes('..')||p.startsWith('.git/'))return false;if(w){const x=['.github/','database/','migrations/','validation/'];if(x.some(v=>p.startsWith(v))||['quran_research.db','schema.sql'].includes(p))return false}return true}
async function gh(e,p,i={}){if(!e.GITHUB_TOKEN)throw Error('GITHUB_TOKEN is not configured.');const r=await fetch(API+p,{...i,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+e.GITHUB_TOKEN,'X-GitHub-Api-Version':'2026-03-10','User-Agent':'al-quran-research-project-agent',...(i.headers||{})}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw Error('GitHub HTTP '+r.status+': '+String(d?.message||t).slice(0,500));return d}
function b64(s){const a=new TextEncoder().encode(s);let x='';for(const b of a)x+=String.fromCharCode(b);return btoa(x)}
function stamp(){return new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}
function identity(m){m=m.toLowerCase();let bn='আরিফ',la='arif',type='general';if(/icon|আইকন/.test(m)){bn='শাহীন';la='shaheen';type='icon-system'}else if(/ai|agent|এআই|এজেন্ট|engine|সিস্টেম শক্ত/.test(m)){bn='শাহীন';la='shaheen';type='ai-engine'}else if(/chat|চ্যাট|ui|ইন্টারফেস/.test(m)){bn='শামীম';la='shamim';type='chat-ui'}else if(/reader|কুরআন|আয়াত|আয়াত|পাঠ|translation|উচ্চারণ/.test(m)){bn='সুমন';la='sumon';type='reader-data'}else if(/test|browser|verify|যাচাই|পরীক্ষা/.test(m)){bn='নাঈম';la='naim';type='verification'}else if(/notification|নোটিফিকেশন|update|আপডেট/.test(m)){bn='রাকিব';la='rakib';type='notification'}const id='AGENT-'+la.toUpperCase()+'-'+stamp(),task='TASK-'+stamp()+'-'+Math.random().toString(36).slice(2,7).toUpperCase(),branch='agent/'+la+'-'+type+'-'+stamp().slice(-8);return{bn,la,type,id,task,branch}}
async function readFile(e,a){const p=String(a.path||''),b=String(a.branch||'main');if(!safePath(p))throw Error('এই path অনুমোদিত নয়।');const d=await gh(e,'/repos/'+repo(e)+'/contents/'+p.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(b));if(d.type!=='file')throw Error('এটি file নয়।');if(Number(d.size||0)>MAX_FILE)throw Error('ফাইলটি engine-এর সীমার চেয়ে বড়।');const bin=atob(String(d.content||'').replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return{path:p,branch:b,sha:d.sha,size:d.size,content:new TextDecoder().decode(bytes)}}
async function listDir(e,a){const p=String(a.path||''),b=String(a.branch||'main');if(!safePath(p))throw Error('এই path অনুমোদিত নয়।');const d=await gh(e,'/repos/'+repo(e)+'/contents/'+p.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(b));if(!Array.isArray(d))throw Error('Directory পাওয়া যায়নি।');return d.map(x=>({name:x.name,path:x.path,type:x.type,size:x.size||0}))}
async function searchCode(e,a){const q=String(a.query||'').trim();if(!q)throw Error('search query প্রয়োজন।');const d=await gh(e,'/search/code?q='+encodeURIComponent(q+' repo:'+repo(e)));return(d.items||[]).slice(0,20).map(x=>({path:x.path,html_url:x.html_url}))}
async function createBranch(e,a){const b=String(a.branch||''),base=String(a.base||'main');if(!isAgentBranch(b))throw Error('শুধু agent/* branch তৈরি করা যাবে।');if(base!=='main'&&!isAgentBranch(base))throw Error('base branch অনুমোদিত নয়।');const r=await gh(e,'/repos/'+repo(e)+'/git/ref/heads/'+encodeURIComponent(base));const c=await gh(e,'/repos/'+repo(e)+'/git/refs',{method:'POST',body:JSON.stringify({ref:'refs/heads/'+b,sha:r.object.sha}),headers:{'Content-Type':'application/json'}});return{branch:b,base,sha:c.object.sha}}
async function writeFile(e,a){const p=String(a.path||''),b=String(a.branch||'');if(!isAgentBranch(b))throw Error('Write করতে agent/* branch বাধ্যতামূলক।');if(!safePath(p,true))throw Error('এই protected path-এ agent write করতে পারবে না.');const c=String(a.content||'');if(c.length>MAX_FILE)throw Error('ফাইলটি engine-এর সীমার চেয়ে বড়.');let old=null;try{old=await gh(e,'/repos/'+repo(e)+'/contents/'+p.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(b))}catch{}const payload={message:String(a.message||'AI agent change'),content:b64(c),branch:b};if(old?.sha)payload.sha=old.sha;const d=await gh(e,'/repos/'+repo(e)+'/contents/'+p.split('/').map(encodeURIComponent).join('/'),{method:'PUT',body:JSON.stringify(payload),headers:{'Content-Type':'application/json'}});return{path:p,branch:b,created:!old?.sha,commit_sha:d.commit?.sha||null}}
const TOOLS=[
{name:'project_read_file',description:'Read a project file before editing.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},
{name:'project_list_directory',description:'List project files.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'}},required:['path']}},
{name:'project_search_code',description:'Search project code.',parameters:{type:'object',properties:{query:{type:'string'}},required:['query']}},
{name:'project_create_branch',description:'Create isolated agent/* branch.',parameters:{type:'object',properties:{branch:{type:'string'},base:{type:'string'}},required:['branch']}},
{name:'project_write_file',description:'Write text only to agent/* branch; protected paths are blocked.',parameters:{type:'object',properties:{path:{type:'string'},branch:{type:'string'},content:{type:'string'},message:{type:'string'}},required:['path','branch','content','message']}}
];
async function tool(e,n,a){if(n==='project_read_file')return readFile(e,a);if(n==='project_list_directory')return listDir(e,a);if(n==='project_search_code')return searchCode(e,a);if(n==='project_create_branch')return createBranch(e,a);if(n==='project_write_file')return writeFile(e,a);throw Error('Unknown tool: '+n)}
async function gemini(e,h,meta){if(!e.GEMINI_API_KEY)throw Error('GEMINI_API_KEY is not configured.');const model=e.GEMINI_MODEL||'gemini-2.5-flash';const sys=`তুমি আল-কুরআন গবেষণা প্রকল্পের autonomous Project Agent। Agent Name: ${meta.bn}; Agent ID: ${meta.id}; Task ID: ${meta.task}; Work Type: ${meta.type}; Branch: ${meta.branch}. প্রথমে relevant instruction/state/code পড়বে, তারপর root cause ও plan নির্ধারণ করবে। সব কাজ isolated agent branch-এ করবে। main, merge, production deploy এবং protected paths স্পর্শ করবে না। inherited task হলে predecessor handoff পড়বে। শেষে কী পড়েছ, কী বদলেছ, changed files, commits, tests, verification, remaining work এবং approval/deployment state বাংলায় জানাবে। test ছাড়া VERIFIED/LIVE বলবে না।`;let c=h.slice();for(let t=0;t<MAX_TURNS;t++){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':e.GEMINI_API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:sys}]},contents:c,tools:[{functionDeclarations:TOOLS}],generationConfig:{maxOutputTokens:4096,temperature:.1}})});const d=await r.json();if(!r.ok)throw Error('Gemini HTTP '+r.status+': '+String(d?.error?.message||'').slice(0,400));const mc=d?.candidates?.[0]?.content;if(!mc)throw Error('Gemini response missing content.');const calls=(mc.parts||[]).filter(p=>p.functionCall);if(!calls.length)return{answer:(mc.parts||[]).map(p=>p.text||'').join('').trim(),model,turns:t+1};c.push(mc);const rs=[];for(const p of calls){let z;try{z=await tool(e,p.functionCall.name,p.functionCall.args||{})}catch(x){z={ok:false,error:String(x?.message||x)}}rs.push({functionResponse:{name:p.functionCall.name,response:{result:z}}})}c.push({role:'user',parts:rs})}throw Error('Agent tool loop limit reached.')}
export default{async fetch(req,env){const o=req.headers.get('Origin')||'';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(o)});if(req.method==='GET')return json({ok:true,service:'al-quran-research-project-agent',version:env.AGENT_VERSION||'1.1.0',isolated:true,identity_registry:true,task_ledger:true,write_scope:'agent/* only',merge:false,deploy:false},200,o);if(req.method!=='POST')return json({ok:false,error:'POST/GET only'},405,o);if(!env.AGENT_ACCESS_TOKEN||req.headers.get('Authorization')!=='Bearer '+env.AGENT_ACCESS_TOKEN)return json({ok:false,error:'Unauthorized'},401,o);try{const body=await req.json(),msg=String(body?.message||'').trim();if(!msg)return json({ok:false,error:'message required'},400,o);if(msg.length>10000)return json({ok:false,error:'message too large'},413,o);const meta=identity(msg),r=await gemini(env,[{role:'user',parts:[{text:msg}]}],meta);return json({ok:true,answer:r.answer,provider:r.model,agent_version:env.AGENT_VERSION||'1.1.0',identity:{agent_name:meta.bn,agent_id:meta.id,task_id:meta.task_id||meta.task,work_type:meta.type,branch:meta.branch},isolated:true,merge:false,deploy:false},200,o)}catch(e){return json({ok:false,error:'PROJECT_AGENT_FAILED',detail:String(e?.message||e).slice(0,600)},500,o)}}};
