const $=id=>document.getElementById(id);let mode='general',controller=null,speaking=true,recognition=null;
const api='https://al-quran-research.mosharroff0000.workers.dev/';
const toastEl=$('toast');function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toastEl.classList.remove('show'),1800)}
function add(t,c){const x=document.createElement('div');x.className='bubble '+c;x.textContent=t;$('messages').appendChild(x);$('messages').scrollTop=$('messages').scrollHeight}
function say(t){if(!speaking||!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='bn-BD';u.rate=.92;speechSynthesis.speak(u)}
function fallback(){const map={word:'শব্দ গবেষণা মোড সক্রিয়। Root/ধাতু, Lemma, Morphology ও অর্থপরিসর নিয়ে গবেষণার কাঠামো প্রস্তুত।',ayah:'আয়াত বিশ্লেষণ মোড সক্রিয়। ভাষা, শব্দ, ব্যাকরণ ও প্রসঙ্গভিত্তিক গবেষণা করা হবে।',math:'গাণিতিক গবেষণা মোড সক্রিয়। যাচাইকৃত dataset ছাড়া কোনো সংখ্যা অনুমান করা হবে না।',concordance:'একই শব্দ অনুসন্ধান মোড সক্রিয়। শব্দের বিভিন্ন ব্যবহার একত্র করা হবে।',translation:'অনুবাদ গবেষণা মোড সক্রিয়। মূল শব্দ, প্রসঙ্গ ও অনুবাদ তুলনা করা হবে।',tafsir:'তাফসির মোড সক্রিয়। নির্বাচিত তাফসিরের source ও উদ্ধৃতি ধরে গবেষণা করা হবে।',compare:'তুলনামূলক অনুবাদ মোড সক্রিয়। একাধিক অনুবাদ পাশাপাশি বিশ্লেষণ করা হবে।',id:'Research ID মোড সক্রিয়। গবেষণা ফলাফলের স্থায়ী ID তৈরি ও অনুসরণ করা যাবে।'};return map[mode]||'আল-কুরআন গবেষণা সহকারী প্রস্তুত। বাংলায় প্রশ্ন লিখুন অথবা মাইক্রোফোন চাপ দিয়ে বলুন।'}
async function send(){const q=$('input').value.trim();if(!q)return;$('input').value='';add(q,'user');$('status').textContent='উত্তর তৈরি হচ্ছে…';controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,mode,language:'bn'}),signal:controller.signal});const d=await r.json();if(!r.ok||!d.answer)throw Error();add(d.answer,'ai');say(d.answer);$('status').textContent='বাংলা AI চ্যাট প্রস্তুত'}catch(e){if(e.name==='AbortError'){$('status').textContent='AI উত্তর থামানো হয়েছে';return}const a='AI সংযোগে সমস্যা হয়েছে। স্থানীয় গবেষণা সহকারী সক্রিয় হয়েছে।\n\n'+fallback();add(a,'ai');say(a);$('status').textContent='স্থানীয় সহকারী সক্রিয়'}finally{clearTimeout(timer);controller=null}}
$('send').onclick=send;$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
$('speaker').onclick=()=>{speaking=!speaking;$('speaker').textContent=speaking?'◒':'◌';if(!speaking)window.speechSynthesis?.cancel();toast(speaking?'পাঠ শোনানো চালু':'পাঠ শোনানো বন্ধ')};$('stopSpeak').onclick=()=>{window.speechSynthesis?.cancel();toast('পাঠ থামানো হয়েছে')};$('stop').onclick=()=>{controller?.abort();window.speechSynthesis?.cancel();$('status').textContent='AI উত্তর থামানো হয়েছে'};$('clear').onclick=()=>{$('messages').innerHTML='';$('status').textContent='চ্যাট পরিষ্কার হয়েছে';toast('চ্যাট পরিষ্কার হয়েছে')};
$('menu').onclick=()=>$('drawer').classList.toggle('open');$('more').onclick=()=>$('drawer').classList.toggle('open');$('close').onclick=()=>$('drawer').classList.remove('open');
$('plus').onclick=()=>toast('ফাইল, ছবি, নোট ও গবেষণা context সংযুক্তির জায়গা প্রস্তুত');
$('mic').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('status').textContent='এই ব্রাউজারে বাংলা voice input নেই';return}if(recognition){recognition.stop();return}recognition=new SR();recognition.lang='bn-BD';recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{$('status').textContent='শুনছি… বাংলায় বলুন'};recognition.onresult=e=>{$('input').value=e.results[0][0].transcript;send()};recognition.onerror=()=>{$('status').textContent='Voice input বন্ধ হয়েছে';recognition=null};recognition.onend=()=>{recognition=null;if($('status').textContent.startsWith('শুনছি'))$('status').textContent='বাংলা AI চ্যাট প্রস্তুত'};recognition.start()};
function setMode(next,label){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));$('status').textContent='মোড: '+label;toast(label+' মোড সক্রিয়')}
document.querySelectorAll('.mode[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode,b.textContent.trim()));document.querySelectorAll('.drawer [data-mode]').forEach(b=>b.onclick=()=>{setMode(b.dataset.mode,b.textContent.trim());$('drawer').classList.remove('open')});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{const t=b.dataset.tool;if(t==='arabic'||t==='translation'||t==='root'){sessionStorage.setItem('aqr:tool',t);location.href='../../dynamic-reader.html?tool='+encodeURIComponent(t)}else toast('বাংলা উচ্চারণ গবেষণা টুল প্রস্তুত')});
$('nextMode').onclick=()=>{const modes=['general','word','tafsir','compare'];const i=modes.indexOf(mode);setMode(modes[(i+1)%modes.length],document.querySelector('.mode[data-mode="'+modes[(i+1)%modes.length]+'"]')?.textContent.trim()||'সাধারণ প্রশ্ন')};
document.querySelectorAll('.example').forEach(b=>b.onclick=()=>{$('input').value=b.dataset.q;$('input').focus()});
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{const tab=b.dataset.tab;const map={file:'ফাইল',image:'ছবি',copy:'কপি',bookmark:'বুকমার্ক',note:'নোট'};if(tab==='ai')return;if(tab==='file'||tab==='image'){toast(map[tab]+' সংযুক্তি প্রস্তুত');return}if(tab==='bookmark'||tab==='note'){toast(map[tab]+' সিস্টেম প্রস্তুত');return}toast(map[tab]+' অপশন')});
document.addEventListener('click',e=>{if(e.target.closest('.drawer')||e.target.closest('#menu')||e.target.closest('#more'))return;const d=$('drawer');if(d.classList.contains('open'))d.classList.remove('open')});
